### PR TITLE
Normalize composer.json

### PR DESCRIPTION
**Pull request by lucasmichot**
Check `composer.json` normalization in CI workflow: see failing test here https://github.com/osiset/laravel-shopify/pull/561/checks?check_run_id=1040588204#step:6:5

---

Add support section and extra config to composer.json file and normalize the `composer.json` file (by running `composer normalize`)

### CODE REVIEW

**Comment by osiset** [comment]
Was a small conflict due to previous PR to add Laravel 8 support.
Pulled in your changes, resolved the conflict, re-ran the normalize and seems to be fine now (I hope).
Thanks!

**Comment by osiset** [comment]
@lucasmichot Any idea why Actions seems odd?

image

The diff doesn't make sense. It appears to be seeing dev requirements inside the standard requirements.

Running `composer normalize --dry-run` locally produces a positive result. Caching issue somewhere on Github's side maybe?

**Comment by lucasmichot** [comment]
This seems like a caching issue.
But nothing to worry about.
I guess this will be resolved with a fresh PR on top of `master` 👍

**Comment by osiset** [comment]
Confirmed. I've merged in your latest PRs and fixed one minor issue, the action seems to pass now.

**Pull request merged**
