### PR TITLE
Adding support for Laravel 9

### PR DESCRIPTION
**Pull request by steveperrycreative**

### CODE REVIEW

**Comment by lucasmichot** [comment]
Thanks @steveperrycreative , can you also add the associated version in the CI strategy ?

**Comment by steveperrycreative** [comment]
Yes @lucasmichot I'll take a look when I get chance.

Thanks.

**Review by lucasmichot — APPROVED** [review]

**Comment by lucasmichot** [comment]
I have added them @steveperrycreative

**Comment by lucasmichot** [comment]
Closes #1090

**Comment by adrianmihaila** [comment]
@osiset can you please help us with a review?

**Comment by litalboa** [comment]
when it will be approved?

**Review by Kyon147 — APPROVED** [review]
Looks good to me too.

**Comment by kamalpal** [comment]
@osiset Please review it.

**Comment by jamescowie** [comment]
I tested this branch and when trying to publish the config I get:

```
 php artisan vendor:publish --tag=shopify-config
No publishable resources for tag [shopify-config].
```

I'm using composer repositories to ensure I get your branch with Laravel 9 fixies in place. 

Is this expected or I am missing something, going to dive into this part shortly to see if it was me.

**Comment by rizwanWixpa098** [comment]
@osiset Hello,
I'm trying install osiset package on laravel 9 but I'm having errors. Have you added the support for laravel 9 
image

**Comment by abubakar0101** [comment]
osiset still not install on laravel 9 and give error below

**### Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires osiset/laravel-shopify ^17.1 -> satisfiable by osiset/laravel-shopify[v17.1.0, v17.1.1, 17.1.x-dev].
    - osiset/laravel-shopify[v17.1.0, ..., 17.1.x-dev] require laravel/framework ^7.0 || ^8.0 -> found laravel/framework[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.11).**

**Comment by rizwanWixpa098** [comment]
I tried to install v17 of osiset but got these errors as well
image

**Comment by zulunran** [comment]
@osiset 
I am facing a problem  to installing ossiset package  version 17  and 16  in laravel 9   

image

**Comment by lucasmichot** [comment]
@rizwanWixpa098 @abubakar0101 @zulunran 

Are you reporting a problem especially with this branch ?
Or just the fact that this package does not yet support Laravel 9.x ?

**Comment by abubakar0101** [comment]
> @rizwanWixpa098 @abubakar0101 @zulunran
> 
> Are you reporting a problem especially with this branch ? Or just the fact that this package does not yet support Laravel 9.x ?



> 

Yes this package does not yet support Laravel 9.x  and not install on laravel 9

**Comment by zulunran** [comment]
> @rizwanWixpa098 @abubakar0101 @zulunran
> 
> Are you reporting a problem especially with this branch ? Or just the fact that this package does not yet support Laravel 9.x ?

this package is not supported yet  for larave9

**Comment by lucasmichot** [comment]
Yes, as of this PR implementing Laravel 9.x support is obviously still open.

When Tyler will have reviewed it, it will be merged and a new release will be created.

**Comment by zulunran** [comment]
thanks for responding 
how long it will take to reviewed by @Tyler

**Comment by rizwanWixpa098** [comment]
> @rizwanWixpa098 @abubakar0101 @zulunran
> 
> Are you reporting a problem especially with this branch ? Or just the fact that this package does not yet support Laravel 9.x ?

I'm having problem with installation of package in laravel 9 so I wanted to know either the package support laravel 9 or not??

**Comment by lucasmichot** [comment]
> thanks for responding how long it will take to reviewed by @tyler

Tyler, not `@tyler`

I don't know when, we all have day jobs and family chores

**Comment by lucasmichot** [comment]
> > @rizwanWixpa098 @abubakar0101 @zulunran
> > Are you reporting a problem especially with this branch ? Or just the fact that this package does not yet support Laravel 9.x ?
> 
> I'm having problem with installation of package in laravel 9 so I wanted to know either the package support laravel 9 or not??
 
If this PR is not merged, then it does not support Laravel 9.x

**Comment by rizwanWixpa098** [comment]
> > > @rizwanWixpa098 @abubakar0101 @zulunran
> > > Are you reporting a problem especially with this branch ? Or just the fact that this package does not yet support Laravel 9.x ?
> > 
> > 
> > I'm having problem with installation of package in laravel 9 so I wanted to know either the package support laravel 9 or not??
> 
> If this PR is not merged, then it does not support Laravel 9.x

Okay Thanks for your response

**Review by abubakar0101 — COMMENTED** [review]
I will changes in my fork same as you describe here, and I will install osiset project after changes locally but cmd return error for installation So tell me please what I do for installing osiset in laravel 9.

**Comment by smartdatasoft** [comment]
Hello, any update for review and approval it. How can we use the test package
thank you

**Comment by francescomalatesta** [comment]
Hi, is there any news about this? May I help somehow? Would love to use it with my next app! :) Thanks for all your work on this package, it's a real game-changer for me.

**Review by Jamesking56 — APPROVED** [review]

**Comment by npabisz** [comment]
5 months later and there is still no support for Laravel 9 🙄

**Comment by lucasmichot** [comment]
5 years later and there is still no support from Shopify 🙄

**Review by osiset — APPROVED** [review]
Good to merge when ready.

**Comment by araschy** [comment]
Thanks for the work everyone. Looking forward to building new projects when this gets merged.

**Comment by joeelia** [comment]
This is an amazing accomplishment. Great community <3 . I can almost taste this PR getting merged, were so close!

**Comment by itrack** [comment]
The PR looks ok, @osiset you can merge?

**Comment by nahid** [comment]
Is there any updates?

**Comment by ncpope** [comment]
I saw that this was going to be merged with #1191. Is there anything else that needs to be done before we can release it? Happy to help in any way.

**Comment by Kyon147** [comment]
Hey @ncpope 

It's going to be merged into the main branch first with PR #1191 and both together will have a versioned release.

**Pull request merged**
