### PR TITLE
Add variables command

### PR DESCRIPTION
**Pull request by enmaboya**
You will probably add variables to the .env one way or another.

This command just simplifies the this process

### CODE REVIEW

**Comment by osiset** [comment]
@enmaboya I am fine with this! Maybe the command should be `shopify-app:variables:generate`? Been looking at how other pkgs do commands, seem to be more along the lines of `namespace:section:action`.

Approving running the actions too, so we can see test results.

**Review by osiset — APPROVED** [review]

**Comment by osiset** [comment]
Hmm not sure why actions is not showing up for this PR... @Kyon147 have you seen this happen before?

**Comment by Kyon147** [comment]
@osiset that is strange, we might need to do a blank commit and push in this PR to trigger them. Github might have just had a wobble.

**Comment by osiset** [comment]
@Kyon147 That solved it :/

**Comment by osiset** [comment]
@enmaboya Merged. Maybe add a wiki entry about it if you get time to explain what it does... we probably need a page to explain all commands existing (like this one and webhook) in the future.

**Pull request merged**
