### PR TITLE
UPDATE: Customize Plan & Charge Models and tables name 

### PR DESCRIPTION
**Pull request by ansezz**
Problem:
I can't use the package in an existing project who has the same tables name & Models

Solution:
I have added the ability to customize/extend Charge & Plane Models also the tables name to avoid any conflict if you have an existing database.

New config I have added:
```
    'models' => [
        /*
        * The fully qualified class name of the Charge model.
        */
        'charge' => Osiset\ShopifyApp\Storage\Models\Charge::class,

        /*
        * The fully qualified class name of the Plan model.
        */
        'plan' => Osiset\ShopifyApp\Storage\Models\Plan::class,
    ],

    'table_names' => [
        /*
        * The table name for the Charge model.
        */
        'charges' => 'charges',

        /*
        * The table name for the Plan model.
        */
        'plans' => 'plans',
    ]
```

### CODE REVIEW

**Comment by osiset** [comment]
@ansezz Good idea!

Can you update all `config` to be `Util::getShopifyConfig`.

Example: `config('shopify-app.models.charge')` would be `Util::getShopifyConfig('models.charge')`.

After this, its good to merge :)

**Comment by ansezz** [comment]
@osiset Thank you, 
I did update all of them, you can check now.

**Comment by osiset** [comment]
@ansezz Thanks! Appears to be a syntax error, locally it seems to pass, but I suspect 7.3 you can't init a class that way... ie `new (Util::getShopifyConfig('models.something', Something::class))`, it may need to be:

```php
$kclass = Util::getShopifyConfig('models.something', Something::class);
... new $klass;
```

**Comment by ansezz** [comment]
@osiset Yeah!
It was in PHP 7, I did fix it now
Thanks

**Comment by osiset** [comment]
Passing, thanks for the feature, I'll merge!

**Pull request merged**
