### PR TITLE
Added parameter to billing process

### PR DESCRIPTION
**Pull request by RishabhTayal**
When a merchant accepts/declines billing this will add a parameter 'billing -> success' to the home page route. This way developers can detect when billing is accepted/declined.

### CODE REVIEW

**Comment by osiset** [comment]
@RishabhTayal Good idea, thanks for this. Can you add a test to the BillingController's test file to confirm this works as expected? You can modify the existing tests thats in the file already for accept/decline and test the result of the redirect URL.

**Comment by osiset** [comment]
@RishabhTayal You should be able to assert the parameter comes back on [this test](https://github.com/RishabhTayal/laravel-shopify/blob/billing-parameter/tests/Traits/BillingControllerTest.php#L53)

**Comment by RishabhTayal** [comment]
@osiset Sorry for naive question: Do you have an example in the code of asserting a parameter?

**Comment by Kyon147** [comment]
@osiset I'm assuming this PR is the one you mentioned, I can merge this one and my on together once they are both ready and they can go out together.

**Comment by osiset** [comment]
@Kyon147 This is exactly it, yes!

**Comment by Kyon147** [comment]
Closing in favour of #1244

**Pull request closed without merging**
