### PR TITLE
Update BillingController.php

### PR DESCRIPTION
**Pull request by usmanpakistan**
Added a check in billing controller to redirect to the home route if no charge ID is provided. Fix issue #1174

### CODE REVIEW

**Comment by Kyon147** [comment]
Thanks for looking into this @usmanpakistan it was on my list this week so was happy to see someone else providing a solution 💪 

i've run the tests and a couple are failing, can you please take a look and fix. One of them is a composer allowed plugins, which probably just needs to be added into the package.json as an allowed plugin.

**Comment by Kyon147** [comment]
My PR #1194 should fix the issue with the normalize plugin.

**Comment by Kyon147** [comment]
if you pull in master, it should fix the issue with the allowed plugins error but you'll need to fix the linting issue still.

**Comment by Kyon147** [comment]
@osiset - this is the other breaking change which will get an app rejected.  @usmanpakistan got part the way there but have finished it off and added a test so i can merge this into master today (if you can take a look) and then it can go with release v17.2.0

**Comment by osiset** [comment]
@Kyon147 Will look in an hour, thanks

**Review by osiset — APPROVED** [review]
@Kyon147 All good.

**Pull request merged**
