### PR TITLE
Update old readme info

### PR DESCRIPTION
**Pull request by ItsGageH**
Remove a 3-year old "coming soon"
Remove the roadmap link as the wiki page is empty

### CODE REVIEW

**Comment by ncpope** [comment]
looks good, should also delete the wiki page - https://github.com/osiset/laravel-shopify/wiki/Roadmap

**Comment by Kyon147** [comment]
@ItsGageH - Thanks for the PR

Can you pull in the changes from master that fixes the tests please

**Comment by osiset** [comment]
Good with this, as stated, update your branch and we can merge it.

**Comment by ItsGageH** [comment]
Merged for ya @osiset & @Kyon147 👍

**Comment by Kyon147** [comment]
Thanks @ItsGageH merging in.

**Pull request merged**
