### PR TITLE
added laravel 9

### PR DESCRIPTION
**Pull request by Sanjay-100**
Update composer file compatible with laravel version 9

### CODE REVIEW

**Comment by lucasmichot** [comment]
CI is broken, please fix it @Sanjay-100 
Also please this in the tests strategies

**Comment by lucasmichot** [comment]
Ping @Sanjay-100

**Comment by Kyon147** [comment]
Just adding the `|| 9.0` to composer probably won't be enough. Tests will need to be updated and we will need to make sure that there are not any high / medium impact changes https://laravel.com/docs/9.x/upgrade

One of them is going to be the requirement to be on at least php `8.0.2` so the CI/CD flows might need to be amended.

As @lucasmichot mentioned, @Sanjay-100 can you update your PR as it is broken.

**Comment by lucasmichot** [comment]
Closed by #1100

**Pull request closed without merging**
