### PR TITLE
Test for PHP 8

### PR DESCRIPTION
**Pull request by lucasmichot**
Test for PHP 8

### CODE REVIEW

**Comment by osiset** [comment]
I ran into an issue where the value object package is linked to version 7. Not sure if its active anymore, may require to be forked.

**Comment by osiset** [comment]
Digging more into this.

php-array-of package is locked to ^7.1, composer file would need to be updated to be ^7.1 || ^8.0

That package is used by valueobjects, which is also locked to ^.7.1.

So both packages would need to be updated.

I've done the work for php-array-of and submitted a PR. I'm not sure if the maintainer is active anymore, so if it sits for a bit and is not accepted, I can absorb both packages I guess would be quickest.

**Comment by lucasmichot** [comment]
Hey @osiset , yes the dependency is also locked.
the package has not been updated for years. I feel this is somehow safer to switch to another dependency?
WDYT ?

**Comment by osiset** [comment]
@lucasmichot I'll open the PR today, work is done. I'll leave it for a few days to see if it gets accepted, if not, I'll finish the work and release it to packagist under this namespace and then you can swap the dependency in composer.json to the new namespace and all should work well then.

**Comment by osiset** [comment]
@lucasmichot PR was accepted for php-array-of, so maintainer is still active :) once patch is on packagist, I'll give the maintainer a PR for the other package... then we should be good to go.

**Comment by osiset** [comment]
@lucasmichot Both PRs done, update valueobjects package in composer.json to 0.5 and it'll resolve.

I think Laravel 5.8 needs to be excluded from the matrix for PHP 8.0 if I remember as well.

**Comment by NESTEROVILYASERGEEVICH** [comment]
Hey @osiset,
I am using your package, I need your help with some installation.
Could you please help me?

**Comment by osiset** [comment]
@lucasmichot PHP 8 support is in master now.

Things I did:

- 8.22 is the lowest Laravel which supports PHP 8 and doesn't have reported security issues
- Dropped Laravel 5 and 6
- Modified action to exclude PHP 7.2 with Laravel 8.22 (since Laravel 8.22 wants PHP 7.3 and up)
- Modified action to exclude PHP 8.0 with Laravel 7.0 (since Laravel 7.0 wants PHP 7.2)

**Comment by osiset** [comment]
Ill close this PR for now since PHP8 support was released. Feel free to push any improvements to it however that you see fit :D

**Pull request closed without merging**
