### PR TITLE
fix #675 infinite loop caused by missing itp cookie

### LINKED ISSUE #675: Infinite loop when installing custom app with MS Edge
## Expected Behavior

The app extension is installed. Infinite loop is not happening. "itp" cookie is set.

## Current Behavior

When I click "Install app" in Shopify partner dashboard, an infinite loop starts. It seems to be caused by missing "itp" cookie.

## Failure Information

Read from bottom to top (bottom goes first) and so on, I stop it manually
```
GET / 					302 Found
GET /itp 					302 Found
GET /authenticate/oauth 	200 OK
GET / 					302 Found
GET /itp 					302 Found
GET /authenticate/oauth 	200 OK
GET /                                       302 Found 
GET /itp                                   302 Found 
GET /authenticate/oauth        200 OK   
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create custom app on Shopify, using Laravel and your package.
2. Try to install app from step 1 on test shop using MS Edge browser in private mode (other browsers not tested)
3. Infinite loop starts, observe server logs, browser traffic etc.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: v16.0.0
* Laravel Version: v8.11.2
* PHP Version: 7.4
* Using a toolset: Docker, ngrok

### PR DESCRIPTION
**Pull request by pontifex**
I did not investigate which parameter exactly is causing the issue, just removing all makes a work.

### CODE REVIEW

**Comment by pontifex** [comment]
// after fix tracking

```
GET /authenticate/oauth        200 OK          
GET /                                       302 Found
GET /itp                                   302 Found
GET /authenticate/oauth        200 OK 
```

**Comment by osiset** [comment]
Having ITP check off on the /oauth route may solve the issue. Ill have to look into this one.

**Comment by osiset** [comment]
@pontifex Oddly, I didnt have the issue you described, but today, I tried an install and had your issue.

I adjusted the routes to exclude oauth stuff from ITP checks, and its working again. I've released a patched which should help.

However, if you still have an issue and your PR works, I'll investigate more.

**Comment by pontifex** [comment]
@osiset  Thanks! I will try to manage some time soon (tomorrow?) to make some extra tests after your patch.

**Comment by pontifex** [comment]
@osiset It works perfect now. Thanks again for a quick fix.

**Pull request closed without merging**
