### PR TITLE
Replace all the helpers by a Util class

### PR DESCRIPTION
**Pull request by lucasmichot**
Replace all the helpers by a `Util` class

### CODE REVIEW

**Comment by osiset** [comment]
Hope this merges well with feature/cookieless, thanks a lot!

**Comment by osiset** [comment]
As an update... nice few conflicts but resolved them easily on the cookieless branch. Thanks!

**Comment by lucasmichot** [comment]
I was just looking at your branch 👍 

Why not opening a draft PR for this one ?

**Comment by osiset** [comment]
Thats what I have scheduled to do this afternoon :), no red flags with the cookieless branch finally, I think its in a state to begin pushing it to master.

**Pull request merged**
