### PR TITLE
Adds ability to delete unused script tags

### PR DESCRIPTION
**Pull request by niveshsaharan**
- Adds function to delete script tags
- Automatically delete unused script tags from shop

### CODE REVIEW

**Comment by osiset** [comment]
Thanks for this! Looks fine. Just to confirm though, memory is rusty, the API call only has access to the apps current script tags correct? I wouldn't want it to delete some other app's scripttags.

**Comment by osiset** [comment]
Thanks, merging.

**Comment by osiset** [comment]
@niveshsaharan This has been an ask for webhooks as well, do you think a similar process for webhooks would be beneficial?

**Comment by niveshsaharan** [comment]
@osiset Maybe but I never needed to do this for webhook as we don't normally need our apps to remove existing webhooks.

**Comment by osiset** [comment]
I may duplicate your process and implement this for webhooks as well.

**Comment by niveshsaharan** [comment]
Sounds good. Thank you for the awesome work you're doing.

**Pull request merged**
